// ============================================================================
// Node Palette - Sidebar with draggable node types and quick templates
// ============================================================================

import React from 'react';
import { Pipeline } from '../../models/types';
import { ALL_TEMPLATES } from '../../templates/samplePipelines';

interface PaletteItem {
  type: string;
  label: string;
  icon: string;
  description: string;
  color: string;
}

const PALETTE_ITEMS: PaletteItem[] = [
  {
    type: 'input',
    label: 'Input',
    icon: '📥',
    description: 'Data entry point: manual text, file upload, API, or webhook',
    color: 'bg-green-100 border-green-300',
  },
  {
    type: 'agent',
    label: 'AI Agent',
    icon: '🤖',
    description: 'Configurable AI agent with custom prompt and model',
    color: 'bg-indigo-100 border-indigo-300',
  },
  {
    type: 'condition',
    label: 'Condition',
    icon: '🔀',
    description: 'Branch pipeline based on a condition expression',
    color: 'bg-amber-100 border-amber-300',
  },
  {
    type: 'loop',
    label: 'Loop',
    icon: '🔁',
    description: 'Repeat a section of the pipeline until a condition is met',
    color: 'bg-purple-100 border-purple-300',
  },
  {
    type: 'parallel',
    label: 'Parallel',
    icon: '⚙️',
    description: 'Execute multiple agents simultaneously',
    color: 'bg-teal-100 border-teal-300',
  },
  {
    type: 'code',
    label: 'Code Executor',
    icon: '⚡',
    description: 'Run JavaScript code generated by an AI agent',
    color: 'bg-cyan-100 border-cyan-300',
  },
  {
    type: 'output',
    label: 'Output',
    icon: '📤',
    description: 'Result collector: display, save to file, API, or email',
    color: 'bg-red-100 border-red-300',
  },
];

const TEMPLATE_META: { id: string; icon: string; color: string }[] = [
  { id: 'template-content-writer', icon: '📝', color: 'border-indigo-300 bg-indigo-50' },
  { id: 'template-customer-support', icon: '🎧', color: 'border-amber-300 bg-amber-50' },
  { id: 'template-data-analysis', icon: '📊', color: 'border-emerald-300 bg-emerald-50' },
  { id: 'template-code-review', icon: '🔍', color: 'border-violet-300 bg-violet-50' },
  { id: 'template-job-search', icon: '💼', color: 'border-sky-300 bg-sky-50' },
  { id: 'template-data-fetcher', icon: '⚡', color: 'border-cyan-300 bg-cyan-50' },
];

interface NodePaletteProps {
  onAddNode: (type: string) => void;
  onLoadTemplate: (template: Pipeline) => void;
}

export const NodePalette: React.FC<NodePaletteProps> = ({ onAddNode, onLoadTemplate }) => {
  const handleDragStart = (e: React.DragEvent, item: PaletteItem) => {
    e.dataTransfer.setData('application/pipeline-node', JSON.stringify(item));
    e.dataTransfer.effectAllowed = 'move';
  };

  return (
    <div className="node-palette p-4">
      <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wider mb-3">
        Pipeline Nodes
      </h3>
      <p className="text-xs text-gray-400 mb-4">
        Drag nodes onto the canvas or click to add
      </p>

      <div className="space-y-2">
        {PALETTE_ITEMS.map((item) => (
          <div
            key={item.type}
            draggable
            onDragStart={(e) => handleDragStart(e, item)}
            onClick={() => onAddNode(item.type)}
            className={`
              ${item.color}
              border rounded-lg p-3 cursor-grab active:cursor-grabbing
              hover:shadow-md transition-shadow duration-150
            `}
          >
            <div className="flex items-center gap-2 mb-1">
              <span className="text-lg">{item.icon}</span>
              <span className="font-medium text-sm text-gray-800">{item.label}</span>
            </div>
            <p className="text-xs text-gray-500 pl-8">{item.description}</p>
          </div>
        ))}
      </div>

      {/* Quick Templates Section */}
      <div className="mt-6">
        <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wider mb-3">
          Quick Templates
        </h3>
        <p className="text-xs text-gray-400 mb-3">
          Click to load a fully configured pipeline
        </p>
        <div className="space-y-2">
          {ALL_TEMPLATES.map((template) => {
            const meta = TEMPLATE_META.find((m) => m.id === template.id);
            const agentCount = template.nodes.filter((n) => n.type === 'agent').length;
            const providers = [...new Set(
              template.nodes
                .filter((n) => n.data.agentConfig)
                .map((n) => n.data.agentConfig!.provider)
            )];

            return (
              <button
                key={template.id}
                onClick={() => onLoadTemplate(template)}
                className={`w-full text-left border rounded-lg p-3
                           hover:shadow-md transition-all duration-150
                           ${meta?.color ?? 'border-gray-200 bg-gray-50'}`}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-lg">{meta?.icon ?? '📋'}</span>
                  <span className="text-sm font-medium text-gray-800">{template.name}</span>
                </div>
                <p className="text-xs text-gray-500 mb-2 pl-7">{template.description}</p>
                <div className="flex items-center gap-2 pl-7 flex-wrap">
                  <span className="text-xs bg-white/70 border border-gray-200 rounded px-1.5 py-0.5 text-gray-600">
                    {agentCount} agents
                  </span>
                  <span className="text-xs bg-white/70 border border-gray-200 rounded px-1.5 py-0.5 text-gray-600">
                    {template.nodes.length} nodes
                  </span>
                  {providers.map((p) => (
                    <span
                      key={p}
                      className="text-xs bg-white/70 border border-gray-200 rounded px-1.5 py-0.5 text-gray-500"
                    >
                      {p}
                    </span>
                  ))}
                </div>
                {template.sampleInput && (
                  <div className="mt-2 ml-7 px-2 py-1.5 bg-white/60 border border-gray-200 rounded text-xs text-gray-500 italic truncate">
                    Example: {template.sampleInput.split('\n')[0].slice(0, 60)}
                    {(template.sampleInput.split('\n')[0].length > 60 || template.sampleInput.includes('\n')) ? '...' : ''}
                  </div>
                )}
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
};
